### ISSUE TITLE
confirm client key provisioning is functional

### ISSUE THREAD

**Issue by lazzarello** [verygood-ops/verygood.openvpn#12]
The README implies there is a playbook that will provision client keys, which could be used to test a development server stood up via vagrant. This documentation looks missing. Where is it and how does this work?

**Comment by akhon** [comment]
hey @lazzarello, sorry for delay.

Actually, README contains info how to get client keys, see https://github.com/verygood-ops/verygood.openvpn#generating-client-keys section

Also, there's command example [here](https://github.com/verygood-ops/infra-vault/wiki/How-to-generate-VPN-credentials%3F), but command is very long and hard to remember, so we've created ansible play which promts user for variables and generates keys via that long command. It wasn't merged yet: https://github.com/verygood-ops/infra-vault/pull/274

**Comment by lazzarello** [comment]
thanks, it looks like I duplicated some of your work yesterday since I wasn't aware of this PR. I'm going to clean up my commits in this playbook. How does this playbook interact with the infra-vault repo? Does this playbook need to be included in a unique repo? I would like to merge it into infra-vault if possible.

**Comment by akhon** [comment]
@lazzarello this repo interacts with infra repo via requirements.yml: https://github.com/verygood-ops/infra-vault/blob/vg/requirements.yml
so, we just need to update that file, and repack infra package

**Comment by lazzarello** [comment]
client keys require an EC2 specific variable to be set. This fails in local dev mode. Need a sensible default to get the IP address from the vagrant file.

**Comment by lazzarello** [comment]
fixed in 2f55824
