### ISSUE TITLE
citadel bucket does not include encrypted values

### ISSUE THREAD

**Issue by lazzarello** [verygood-ops/verygood.openvpn#13]
This playbook accesses S3 to obtain both server and client keys. It uses the bucket labled citadel, though the contents of this bucket are not encrypted. I confirmed this through using the S3 dashboard to manually download the client key.

**Comment by akhon** [comment]
@lazzarello we are using server-side encryption for citadel bucket, see bucket policy:
```
"s3:x-amz-server-side-encryption": "AES256"
```

**Comment by mahmoudimus** [comment]
IMO this should not be the job of the citadel bucket or this playbook to encrypt values if server side encryption is not desired.

**Comment by lazzarello** [comment]
okay cool. I didn't understand how S3 encryption worked completely. I'm comfortable with this process.
