### ISSUE TITLE
Open UDP port on NAT machine

### ISSUE THREAD

**Issue by mahmoudimus** [verygood-ops/verygood.openvpn#2]
Need to open up the OpenVPN port on the NAT machine.

**Comment by mjallday** [comment]
UDP port 1194 right @mahmoudimus 
?

**Comment by mahmoudimus** [comment]
yup!

Mahmoud Abdelkader
Very Good Group
CEO & Co-Founder
(m) 410-236-6551
(e) mahmoud@vgs.io
